### ISSUE TITLE
DelaTable function returns all versions of delta table

### ISSUE THREAD

**Issue by nitzmali** [jeppe742/DeltaLakeReader#12]
from deltalake import DeltaTable
df = DeltaTable("path_to_delta_table",file_system=fs).to_pandas()

In the latest release of 0.2.2, I have been trying to read a 
<img width="1690" alt="delta_table_issue" src="https://user-images.githubusercontent.com/26385244/119203663-70559280-ba48-11eb-9cd2-c83f1d1fa3f7.png">
delta table from S3 which only updates few rows. When I do a read on full delta table. The dataframe has both initial value and updated value. But, I only need the latest snapshot which is the latest update. Not all the updates ever done. Am I missing something? For validation, I verified by reading through Spark context and It returns only the latest snapshot. Any help? 

For reference I have attached a snapshot of read from DeltaTable and read from Spark and the data frame has two and one row respectively.

**Comment by jeppe742** [comment]
Hey @nitzmali,
Thanks for spotting this. I had a small mistake in the code that should be fixed in #13 
Also published the fix in version 0.2.3, if you want to test it out

**Comment by nitzmali** [comment]
Thanks as a lot @jeppe742 for quick response. It perfectly works fine now. Cheers.
