### ISSUE TITLE
Failing to read first 10 versions of the table

### ISSUE THREAD

**Issue by avaneeshqb** [jeppe742/DeltaLakeReader#41]
In #39, a new piece of code was added to raise error when `_last_checkpoint` is not present. 
But since that change, I can't read any delta version before at least 10 versions of the table are added as the `_last_checkpoint` file is only created after at least 10 versions. 

Would it better to instead look for *.json or some other file to validate if it's a delta table?

**Comment by jeppe742** [comment]
hmm, good point @avaneeshqb.

Let me quickly fix it. Perhaps we should just look for the _delta_log folder instead. 
That should always exist

**Comment by jeppe742** [comment]
@avaneeshqb Think i managed to fix it. Please have a look at the newest version 😃
