### ISSUE TITLE
Problem with reading delta lake tables using HDFSFileSystem

### ISSUE THREAD

**Issue by yanglin-code** [jeppe742/DeltaLakeReader#46]
Using `from fsspec.implementations.hdfs import PyArrowHDFS` FileSystem and `file_system = PyArrowHDFS("127.0.0.1", 9000, "root")` to init it.
Got errors :
`Traceback (most recent call last):
  File "/hadoop/read.py", line 353, in <module>
    readData()
  File "/hadoop/read.py", line 344, in readData
    df1 = DeltaTable('/zy/example_table_path', file_system=file_system).to_table(filter=ds.field("id") >= 100).to_pandas()
  File "/hadoop/read.py", line 147, in __init__
    self._as_newest_version()
  File "/hadoop/read.py", line 258, in _as_newest_version
    self._apply_partial_logs(version=self.checkpoint + 9)
  File "/hadoop/read.py", line 216, in _apply_partial_logs
    print(list(self.filesystem.open(log_file)))
TypeError: 'HDFSFile' object is not iterable
`

**Comment by jeppe742** [comment]
Hey @yanglin-code.
Would you be able to try using the `fsspec.implementations.arrow.HadoopFileSystem` instead? (see [docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.arrow.HadoopFileSystem ))

Seems like the [`PyArrowHDFS`](https://github.com/fsspec/filesystem_spec/blob/025d846db553f7498c106326ac005656ebfa3bb7/fsspec/implementations/hdfs.py#L221)  had a very limited implementation, only implementing `seek`, but not stuff like `__iter__` or ` __next__`.
For comparison the [`arrow.HadoopFileSystem`](https://github.com/fsspec/filesystem_spec/blob/7077f7fca78368a93bc9bd12f48e78ad4c3f8f30/fsspec/implementations/arrow.py#L185), should implement these, by inheriting from `io.IOBase`

If you look in the latest version of `fsspec` [docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations) or the [`master`](https://github.com/fsspec/filesystem_spec/tree/master/fsspec/implementations) branch, you will also see that the `fsspec.implementations.hdfs` has been deprecated and removed.


Let me know if this resolves the issue

**Comment by yanglin-code** [comment]
> Hey @yanglin-code. Would you be able to try using the `fsspec.implementations.arrow.HadoopFileSystem` instead? (see [docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.arrow.HadoopFileSystem))
> 
> Seems like the [`PyArrowHDFS`](https://github.com/fsspec/filesystem_spec/blob/025d846db553f7498c106326ac005656ebfa3bb7/fsspec/implementations/hdfs.py#L221) had a very limited implementation, only implementing `seek`, but not stuff like `__iter__` or ` __next__`. For comparison the [`arrow.HadoopFileSystem`](https://github.com/fsspec/filesystem_spec/blob/7077f7fca78368a93bc9bd12f48e78ad4c3f8f30/fsspec/implementations/arrow.py#L185), should implement these, by inheriting from `io.IOBase`
> 
> If you look in the latest version of `fsspec` [docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations) or the [`master`](https://github.com/fsspec/filesystem_spec/tree/master/fsspec/implementations) branch, you will also see that the `fsspec.implementations.hdfs` has been deprecated and removed.
> 
> Let me know if this resolves the issue

Thank you for your reply.I tried it but mabye some parameters errors or what,errors like 
this`(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
hdfsBuilderConnect(forceNewInstance=1, nn=hdfs://192.168.6.124, port=50070, kerbTicketCachePath=(NULL), userName=root) error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
/arrow/cpp/src/arrow/status.cc:137: Failed to disconnect hdfs client: IOError: HDFS hdfsFS::Disconnect failed. Detail: [errno 9] 错误的文件描述符
Traceback (most recent call last):
  File "/hadoop/read.py", line 356, in <module>
    readData()
  File "/hadoop/read.py", line 331, in readData
    file_system = HadoopFileSystem(host="192.168.6.124",port=50070, user="root")
  File "/root/anaconda3/lib/python3.9/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/fsspec/implementations/arrow.py", line 222, in __init__
    fs = HadoopFileSystem(
  File "pyarrow/_hdfs.pyx", line 96, in pyarrow._hdfs.HadoopFileSystem.__init__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: HDFS connection failed
`

**Comment by yanglin-code** [comment]
> Hey @yanglin-code. Would you be able to try using the `fsspec.implementations.arrow.HadoopFileSystem` instead? (see [docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.arrow.HadoopFileSystem))
> 
> Seems like the [`PyArrowHDFS`](https://github.com/fsspec/filesystem_spec/blob/025d846db553f7498c106326ac005656ebfa3bb7/fsspec/implementations/hdfs.py#L221) had a very limited implementation, only implementing `seek`, but not stuff like `__iter__` or ` __next__`. For comparison the [`arrow.HadoopFileSystem`](https://github.com/fsspec/filesystem_spec/blob/7077f7fca78368a93bc9bd12f48e78ad4c3f8f30/fsspec/implementations/arrow.py#L185), should implement these, by inheriting from `io.IOBase`
> 
> If you look in the latest version of `fsspec` [docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations) or the [`master`](https://github.com/fsspec/filesystem_spec/tree/master/fsspec/implementations) branch, you will also see that the `fsspec.implementations.hdfs` has been deprecated and removed.
> 
> Let me know if this resolves the issue

Thank you for your reply.I tried it but mabye some parameters errors or what,errors like this:
`(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.) hdfsBuilderConnect(forceNewInstance=1, nn=hdfs://192.168.6.124, port=50070, kerbTicketCachePath=(NULL), userName=root) error: (unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.) /arrow/cpp/src/arrow/status.cc:137: Failed to disconnect hdfs client: IOError: HDFS hdfsFS::Disconnect failed. Detail: [errno 9] 错误的文件描述符 Traceback (most recent call last): File "/hadoop/read.py", line 356, in <module> readData() File "/hadoop/read.py", line 331, in readData file_system = HadoopFileSystem(host="192.168.6.124",port=50070, user="root") File "/root/anaconda3/lib/python3.9/site-packages/fsspec/spec.py", line 68, in __call__ obj = super().__call__(*args, **kwargs) File "/root/anaconda3/lib/python3.9/site-packages/fsspec/implementations/arrow.py", line 222, in __init__ fs = HadoopFileSystem( File "pyarrow/_hdfs.pyx", line 96, in pyarrow._hdfs.HadoopFileSystem.__init__ File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status OSError: HDFS connection failed`

**Comment by yanglin-code** [comment]
Thank you for your reply.I tried it but mabye some parameters errors or what,errors like this:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.) hdfsBuilderConnect(forceNewInstance=1, nn=hdfs://192.168.6.124, port=50070, kerbTicketCachePath=(NULL), userName=root) error: (unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.) /arrow/cpp/src/arrow/status.cc:137: Failed to disconnect hdfs client: IOError: HDFS hdfsFS::Disconnect failed. Detail: [errno 9] 错误的文件描述符 Traceback (most recent call last): File "/hadoop/read.py", line 356, in <module> readData() File "/hadoop/read.py", line 331, in readData file_system = HadoopFileSystem(host="192.168.6.124",port=50070, user="root") File "/root/anaconda3/lib/python3.9/site-packages/fsspec/spec.py", line 68, in __call__ obj = super().__call__(*args, **kwargs) File "/root/anaconda3/lib/python3.9/site-packages/fsspec/implementations/arrow.py", line 222, in __init__ fs = HadoopFileSystem( File "pyarrow/_hdfs.pyx", line 96, in pyarrow._hdfs.HadoopFileSystem.__init__ File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status OSError: HDFS connection failed

**Comment by yanglin-code** [comment]
@jeppe742 
Using this FileSystem:
`file_system = HadoopFileSystem(host="192.168.6.124",port=50070, user="root")`
and got errors below:
`loadFileSystems error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
hdfsBuilderConnect(forceNewInstance=1, nn=hdfs://192.168.6.124, port=50070, kerbTicketCachePath=(NULL), userName=root) error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
/arrow/cpp/src/arrow/status.cc:137: Failed to disconnect hdfs client: IOError: HDFS hdfsFS::Disconnect failed. Detail: [errno 9] 错误的文件描述符
Traceback (most recent call last):
  File "/hadoop/read.py", line 356, in <module>
    readData()
  File "/hadoop/read.py", line 331, in readData
    file_system = HadoopFileSystem(host="192.168.6.124",port=50070, user="root")
  File "/root/anaconda3/lib/python3.9/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/fsspec/implementations/arrow.py", line 222, in __init__
    fs = HadoopFileSystem(
  File "pyarrow/_hdfs.pyx", line 96, in pyarrow._hdfs.HadoopFileSystem.__init__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: HDFS connection failed`

**Comment by jeppe742** [comment]
@yanglin-code 
Somehow it seems like there is something wrong with the way you connect to the HDFS.
I don't have any experience with this, so not sure I can help you here 😞
